### PR TITLE
Develop Stream 2023-05-29

### PR DESCRIPTION
**Pull request by nolmoonen**
- Stop relying on `WIN32` in C++ code (`_WIN32` is the correct macro).
- Added various overloads for `block_sort::sort` to make the interface consistent for the supported algorithms.
- Fixed wrong seed being used in some tests.
- Added script that checks whether the license headers should be updated.
- Added standalone tests for rocPRIM's intrinsics. Fixed the implementation of `MatchAny` and renamed to `match_any` (old name is kept for backwards compatibility).
- Remove `assert` statements from device code, in very specific circumstances these could lead to incorrect code generation.
- Removed references to HCC.
- Increase the Google Benchmark version to 1.6.1 and remove the workaround for the comma issue.
- Remove usage of deprecated `std::random_shuffle`.
- Fix `hipError_t` from being discarded in internal algorithms, to suppress `nodiscard` warnings.
- Remove unused configuration selection case from configuration tuning templates.
- Fix configured test and config tuning benchmark files not getting reconfigured after clean.
- Fixed typos in `temp_storage`.
- Added match-based block histogram.
- Fixed bug in device reduce.
- Added dynamic dispatch and updated the configurations of binary search.
- Update radix sort configuration for gfx906 and add workaround for known issue with specific configuration.
- Added two-way partition primitive `partition_two_way` and improved performance of `partition`.

### CODE REVIEW

**Review by stanleytsang-amd — COMMENTED** [review]
@nolmoonen Could you talk a bit more about the changes to block_sort_merge?

There is a internal compiler change for 5.6 which triggered a test failure in block_sort_merge (with current develop branch).  The compiler team did an analysis and seemed somewhat convinced there was a problem with block_sort_merge itself - perhaps an error with a barrier or fence somewhere (I think warp_sort_stable uses one).  With this PR, the error no longer occurs, so I was wondering if there was any potentially related bug fixes in this PR in regards to block_sort_merge (or any lower-level rocPRIM components used by block_sort_merge?)

**Comment by nolmoonen** [comment]
> @nolmoonen Could you talk a bit more about the changes to block_sort_merge?

The algorithm `rocprim::block_sort` has three algorithms (`block_sort_algorithm`): `bitonic_sort`, `merge_sort`, and `stable_merge_sort`. The underlying implementations in `develop` are `block_sort_bitonic`, `block_sort_merge<Stable=false>`, and `block_sort_merge<Stable=true>`, respectively. I assume you are talking about the test `block_sort_merge` and not `block_sort_merge_stable`. Test `block_sort_merge` tests the algorithm `block_sort_algorithm::merge_sort`.

In this PR, the underlying implementation for the algorithm `block_sort_algorithm::merge_sort` is changed from `block_sort_merge<Stable=false>` to `block_sort_merge<Stable=true>`. The reason for this is performance and the latter has a more flexible interface. The only difference between the two implementations are the warp sort it uses, `rocprim::warp_sort` and `rocprim::detail::warp_sort_stable`.

So, no bug fixes are made, but the warp-level algorithm is changed (again, assuming you only mean test `block_sort_merge` and not also `block_sort_merge_stable`). 

However, the tests for `block_sort` did contain bugs that are fixed in the same commit (https://github.com/ROCmSoftwarePlatform/rocPRIM/pull/434/commits/5abed425563e0a6af5059aa01968652d7f1d2cf7), so perhaps that is the reason for the failure disappearing.

**Comment by stanleytsang-amd** [comment]
> > @nolmoonen Could you talk a bit more about the changes to block_sort_merge?
> 
> The algorithm `rocprim::block_sort` has three algorithms (`block_sort_algorithm`): `bitonic_sort`, `merge_sort`, and `stable_merge_sort`. The underlying implementations in `develop` are `block_sort_bitonic`, `block_sort_merge<Stable=false>`, and `block_sort_merge<Stable=true>`, respectively. I assume you are talking about the test `block_sort_merge` and not `block_sort_merge_stable`. Test `block_sort_merge` tests the algorithm `block_sort_algorithm::merge_sort`.
> 
> In this PR, the underlying implementation for the algorithm `block_sort_algorithm::merge_sort` is changed from `block_sort_merge<Stable=false>` to `block_sort_merge<Stable=true>`. The reason for this is performance and the latter has a more flexible interface. The only difference between the two implementations are the warp sort it uses, `rocprim::warp_sort` and `rocprim::detail::warp_sort_stable`.
> 
> So, no bug fixes are made, but the warp-level algorithm is changed (again, assuming you only mean test `block_sort_merge` and not also `block_sort_merge_stable`).
> 
> However, the tests for `block_sort` did contain bugs that are fixed in the same commit ([5abed42](https://github.com/ROCmSoftwarePlatform/rocPRIM/commit/5abed425563e0a6af5059aa01968652d7f1d2cf7)), so perhaps that is the reason for the failure disappearing.

Hi Nol, sorry, actually I'd like to know about block_sort_merge stable as well.  Thanks.

**Comment by nolmoonen** [comment]
> Hi Nol, sorry, actually I'd like to know about block_sort_merge_stable as well (if any changes were made there or in its tests). Thanks.

The test fixes I mentioned are for the `block_sort` algorithm, so they apply to all of the "subalgorithms", which show up in testing as `rocprim.block_sort_merge`, `rocprim.block_sort_merge_stable`, and `rocprim.block_sort_bitonic`.

Other than that, a minor change is made to `stable_merge_sort`, which fixes a `sort` function overload. Previously, it was in a state where it would not compile when trying to use.

**Review by RobsonRLemos — APPROVED** [review]
StreamHPC:develop_stream_2023_05_29 has been used recently for some additional tests for device scan and device reduce by key using rocPrim across 10 nodes and it has passed.

**Comment by RobsonRLemos** [comment]
@nolmoonen and @Naraenda please merge the PR. Thanks.

**Comment by Beanavil** [comment]
Hi @RobsonRLemos,
I'll answer both questions. We have tested the integration of the present PR with rocThrust/develop and hipCUB/develop:
- rocThrust compiles successfully
- for hipCUB we found a small compilation error, due to the fast_array implementation added in `rocprim/include/rocprim/block/detail/block_reduce_raking_reduce.hpp`. The last commit added to this PR solves this issue, so hipCUB also compiles succesfully and without needing https://github.com/ROCmSoftwarePlatform/hipCUB/pull/253 to be merged.

**Comment by RobsonRLemos** [comment]
Hi @Beanavil,
Thanks for the recent updates and clarification.

**Pull request merged**
