### PR TITLE
309 pytorch unit test failure test tensor creation ops

### PR DESCRIPTION
**Pull request by neon60**
* Fix the comperator operator with bigger bit length than 32.
* Also containes future value implementation
* The reduce/scan algorithm precision issues in the tests has been resolved for half types.

### CODE REVIEW

**Comment by neon60** [comment]
It is also containes:
https://github.com/ROCmSoftwarePlatform/rocPRIM/pull/297

**Comment by neon60** [comment]
@stanleytsang-amd what should we the changelog section title?

**Comment by stanleytsang-amd** [comment]
> @stanleytsang-amd what should we the changelog section title?
[Unreleased rocPRIM-2.10.13 for ROCm 5.1.0]

**Comment by neon60** [comment]
> > @stanleytsang-amd what should we the changelog section title?
> > [Unreleased rocPRIM-2.10.13 for ROCm 5.1.0]

I will update the changelogs.

**Review by stanleytsang-amd — APPROVED** [review]
Waiting for changelog update before merging.

**Comment by neon60** [comment]
> Waiting for changelog update before merging.

Pushed changelog update

**Pull request merged**
