### PR TITLE
StreamHPC 2024-01-16

### PR DESCRIPTION
**Pull request by mfep**
- Config tuning and dynamic dispatch for device segmented radix sort
- Fixes and updates of the generated documentation
- New overloads for `warp_scan::exclusive_scan` that take no initial value
- Fixed warnings and debug build on Windows
- Ensuring that the benchmark suite builds with `-Werror`
- Exposed accumulator type for device scan algorithms
- Fixed incorrect results from shuffled warp exchange (when LogicalWarpSize > BlockSize)
- New overload for `device_adjacent_difference_inplace` that allows separate input and output iterators (for rocThrust)
- Fixed unique_by_key to allow input and output values iterators aliasing
- Skip packaging when project isn't toplevel & allow to disable installation
- Make temp_storage partition object const correct
- Deprecated undocumented `to_exclusive` APIs

### CODE REVIEW

**Comment by stanleytsang-amd** [comment]
@mfep We're seeing a build failure on RHEL9 - I am attaching a build log.  It seems like possibly an error with LLVM itself, but if you can take a look and see if its a problem with the code - if not, then if you can provide any helpful information I can pass it along to the compiler team.  I've also uploaded the RHEL9 docker image used in CI to my dockerhub for you to try.

[rocprim_rhel9_build_error.txt](https://github.com/ROCm/rocPRIM/files/13985227/rocprim_rhel9_build_error.txt)

**Comment by mfep** [comment]
> @mfep We're seeing a build failure on RHEL9 - I am attaching a build log. It seems like possibly an error with LLVM itself, but if you can take a look and see if its a problem with the code - if not, then if you can provide any helpful information I can pass it along to the compiler team. I've also uploaded the RHEL9 docker image used in CI to my dockerhub for you to try.
> 
> [rocprim_rhel9_build_error.txt](https://github.com/ROCm/rocPRIM/files/13985227/rocprim_rhel9_build_error.txt)

@stanleytsang-amd Thank you for the information. I was able to reproduce and investigate the reported failure. The rocPRIM tests and benchmarks were trying to instantiate dumb kernels, and the compiler crashed in a result.

**Details**
- Some of the warp level algorithms in rocPRIM accept a `LogicalWarpSize` parameter, which must be at most the hardware wavefront size. To be able to test and benchmark `LogicalWarpSize == 64` on CDNA, we added such cases, and disabled them at runtime if RDNA hardware was detected. But still, a kernel was generated in such cases, albeit it was slightly modified not to hit the `static_assert` statements in the algorithm's implementation.
- One of such kernels allocated `0` bytes of shared memory, and performed operations on this "allocation". This caused the compiler to crash.

**Actions**
- I've just pushed a few new commits that remove these unused kernels from the source and replaced them with no-op kernels. It makes no sense to waste bytes and cycles to generate such unused kernels. With that, we expect the CI to pass.
- To help the compiler team to investigate the case, and perhaps implement a more graceful error handling for such scenario, I've prepared a stand-alone reproducer. Unfortunately GitHub doesn't allow to upload it as an attachment, so I'll just copy it here:

```c++
#include <hip/hip_runtime.h>

#include <numeric>
#include <vector>

namespace
{

template<unsigned int LogicalWarpSize>
__device__ unsigned int logical_lane_id()
{
    return ::__lane_id() & (LogicalWarpSize - 1); // same as land_id()%WarpSize
}

__device__ inline void wave_barrier()
{
    __builtin_amdgcn_fence(__ATOMIC_RELEASE, "wavefront");
    __builtin_amdgcn_wave_barrier();
    __builtin_amdgcn_fence(__ATOMIC_ACQUIRE, "wavefront");
}

__device__ constexpr unsigned int device_warp_size()
{
    return warpSize;
}

template<class T, unsigned int ItemsPerThread, unsigned int WarpSize>
class warp_exchange
{
    static_assert(WarpSize <= device_warp_size());
    struct storage_type_
    {
        T buffer[WarpSize * ItemsPerThread];
    };

public:
    using storage_type = storage_type_;

    template<class U>
    __device__ void blocked_to_striped(const T (&input)[ItemsPerThread],
                                       U (&output)[ItemsPerThread],
                                       storage_type& storage)
    {
        const unsigned int flat_id = logical_lane_id<WarpSize>();

        for(unsigned int i = 0; i < ItemsPerThread; i++)
        {
            storage.buffer[flat_id * ItemsPerThread + i] = input[i];
        }
        wave_barrier();

        for(unsigned int i = 0; i < ItemsPerThread; i++)
        {
            output[i] = storage.buffer[i * WarpSize + flat_id];
        }
    }
};

inline hipError_t host_warp_size(const int device_id, unsigned int& warp_size)
{
    warp_size = -1;
    hipDeviceProp_t device_prop;
    hipError_t      success = hipGetDeviceProperties(&device_prop, device_id);

    if(success == hipSuccess)
    {
        warp_size = device_prop.warpSize;
    }
    return success;
};

template<class T, unsigned int ItemsPerThread, unsigned int LogicalWarpSize>
__global__ void warp_exchange_kernel(T* d_input, T* d_output)
{
    constexpr unsigned int exchange_warp_size
        = LogicalWarpSize <= device_warp_size() ? LogicalWarpSize : device_warp_size();
    using warp_exchange_type         = warp_exchange<T, ItemsPerThread, exchange_warp_size>;

    // !!! NOTE: num_warps is 0, if LogicalWarpSize > device_warp_size()
    constexpr unsigned int num_warps = device_warp_size() / LogicalWarpSize;
    __shared__ typename warp_exchange_type::storage_type storage[num_warps];

    T thread_data[ItemsPerThread];
    for(unsigned int i = 0; i < ItemsPerThread; i++)
    {
        thread_data[i] = d_input[threadIdx.x * ItemsPerThread + i];
    }

    const unsigned int warp_id = threadIdx.x / LogicalWarpSize;
    warp_exchange_type{}.blocked_to_striped(thread_data, thread_data, storage[warp_id]);

    for(unsigned int i = 0; i < ItemsPerThread; i++)
    {
        d_output[threadIdx.x * ItemsPerThread + i] = thread_data[i];
    }
}

} // namespace

int main()
{
    using T = int;

    constexpr unsigned int logical_warp_size = 64;
    constexpr unsigned int items_per_thread  = 4;

    const int    device_id = 0;
    unsigned int hw_warp_size;
    (void)host_warp_size(device_id, hw_warp_size);

    if(hw_warp_size < logical_warp_size)
    {
        return 0;
    }

    const unsigned int block_size  = hw_warp_size;
    const unsigned int items_count = items_per_thread * block_size;

    std::vector<T> input(items_count);
    std::iota(input.begin(), input.end(), static_cast<T>(0));

    T* d_input{};
    (void)hipMalloc(&d_input, items_count * sizeof(T));
    (void)hipMemcpy(d_input, input.data(), items_count * sizeof(T), hipMemcpyHostToDevice);
    T* d_output{};
    (void)hipMalloc(&d_output, items_count * sizeof(T));
    (void)hipMemset(d_output, 0, items_count * sizeof(T));

    warp_exchange_kernel<T, items_per_thread, logical_warp_size>
        <<<dim3(1), dim3(block_size), 0, 0>>>(d_input, d_output);
    (void)hipGetLastError();
    (void)hipDeviceSynchronize();
}
```

**Review by stanleytsang-amd — APPROVED** [review]
All tests on CI pass.  Checking on hipCUB and rocThrust PRs

**Comment by mfep** [comment]
Rebased to `develop` to resolve conflicts.

**Review by randyh62 — COMMENTED** [review]
looks good to me.

**Comment by stanleytsang-amd** [comment]
@mfep Apologies, can you fix the merge conflicts/rebase for this PR again ASAP?  Due to technical constraints with our CI, this PR needs to be clear of merge conflicts before we can run CI for the hipCUB and rocThrust PRs that depend on this PR.

**Comment by mfep** [comment]
@stanleytsang-amd Sure, done as requested.

**Pull request merged**
