### PR TITLE
Develop stream 20210913

### PR DESCRIPTION
**Pull request by neon60**
* Add block_load_striped and block_store_striped

### CODE REVIEW

**Comment by neon60** [comment]
@stanleytsang-amd Can you sand the root cause of the failure? Maybe we need just a restart.

**Comment by neon60** [comment]
We need this PR for the hipCUB update to 1.14.0.

**Comment by stanleytsang-amd** [comment]
> @stanleytsang-amd Can you sand the root cause of the failure? Maybe we need just a restart.

Sent you an email with the test failure and my comments.

**Review by stanleytsang-amd — APPROVED** [review]

**Comment by doctorcolinsmith** [comment]
Test fail appears unrelated to rocPRIM updates.  Will merge anyways.

**Pull request merged**
