### PR TITLE
Fix compilation error with ALICE

### PR DESCRIPTION
**Pull request by NB4444**
This PR includes all commits from https://github.com/ROCm/rocPRIM/pull/631. That PR should be merge before this one.
This commit adds 2 commits to fix compilation errors when building with ALICE.

### CODE REVIEW

**Review by spolifroni-amd — APPROVED** [review]

**Comment by umfranzw** [comment]
Hello, if we could please rebase this one, that would be great. We'll try to merge it tomorrow.

**Review by umfranzw — APPROVED** [review]
Apologies, it looks like I jumped the gun on the rebase request. Now that #631 is in, this should be the last time we need to do it.

**Comment by RobsonRLemos** [comment]
Hi @NB4444 or @Beanavil can you please rebase this one. Thanks.

**Comment by Beanavil** [comment]
@RobsonRLemos should be rebased now

**Comment by RobsonRLemos** [comment]
Thanks @Beanavil.

**Pull request merged**
