### PR TITLE
Enable gfx12 support

### PR DESCRIPTION
**Pull request by stanleytsang-amd**

### CODE REVIEW

**Comment by Naraenda** [comment]
FYI, in https://github.com/ROCm/rocPRIM/pull/575 we want to deprecate thread load/store https://github.com/ROCm/rocPRIM/pull/575/commits/a1765aebb888426004749608ae6abd12884c309b.

**Comment by stanleytsang-amd** [comment]
> FYI, in #575 we want to deprecate thread load/store [a1765ae](https://github.com/ROCm/rocPRIM/commit/a1765aebb888426004749608ae6abd12884c309b).

Okay good to know. Frankly having to research and update the inline assembly for new GPU architectures was becoming a pain.
That being said, will this also be done in hipCUB?  Will we be losing a (slightly questionable) feature compared to CUB?

**Comment by Naraenda** [comment]
> > FYI, in #575 we want to deprecate thread load/store [a1765ae](https://github.com/ROCm/rocPRIM/commit/a1765aebb888426004749608ae6abd12884c309b).
> 
> Okay good to know. Frankly having to research and update the inline assembly for new GPU architectures was becoming a pain. That being said, will this also be done in hipCUB? Will we be losing a (slightly questionable) feature compared to CUB?

Regarding hipCUB, from a performance point of view, I'd say it's better to eventually drop the inline assembly implementation, since people are more likely to misuse it and be in the way of compiler optimisations. Actually, I _just noticed_ that HIP does have `__ldg`,  `__ldcg`, `__ldca`, but they appear to just be dereferences unless I miss something.

**Review by RobsonRLemos — APPROVED** [review]
LGTM.

**Pull request merged**
