### PR TITLE
Fix device_merge mismatched input iterators for release/rocm-rel-5.3 branch

### PR DESCRIPTION
**Pull request by vince-streamhpc**
https://github.com/ROCmSoftwarePlatform/rocPRIM/pull/381 but targetting `release/rocm-rel-5.3` branch

### CODE REVIEW

**Comment by vince-streamhpc** [comment]
@stanleytsang-amd It works fine on our CI, can you share the Github build errors with me if they are relevant (I don't have access to CI results)?

**Comment by stanleytsang-amd** [comment]
> @stanleytsang-amd It works fine on our CI, can you share the Github/math-ci.rocm build errors with me if they are relevant (I don't have access to CI results)?

The test failures are the warp_sort and block_sort tests, from https://github.com/ROCmSoftwarePlatform/rocPRIM/commit/36a4d355b3ff1d6d64a7c308d0a0798a855679c3.  I had tried to get it cherry-picked to 5.3 in a while ago but it was deemed non-critical.  
Thankfully there are no new failures from this PR so I think it is good from my perspective - I still need to convince the 5.3 managers to allow this cherry-pick.  The deadline has passed.

**Comment by vince-streamhpc** [comment]
> > @stanleytsang-amd It works fine on our CI, can you share the Github/math-ci.rocm build errors with me if they are relevant (I don't have access to CI results)?
> 
> The test failures are the warp_sort and block_sort tests, from [36a4d35](https://github.com/ROCmSoftwarePlatform/rocPRIM/commit/36a4d355b3ff1d6d64a7c308d0a0798a855679c3). I had tried to get it cherry-picked to 5.3 in a while ago but it was deemed non-critical. Thankfully there are no new failures from this PR so I think it is good from my perspective - I still need to convince the 5.3 managers to allow this cherry-pick. The deadline has passed.

Alright, hmm the [36a4d35](https://github.com/ROCmSoftwarePlatform/rocPRIM/commit/36a4d355b3ff1d6d64a7c308d0a0798a855679c3) seems critical to me, but maybe the 5.3 managers believe this small-types vectorization compiler bug will be fixed in the next 5.3 release, so that a patch for this compiler bug is not needed in rocPRIM?

Anyways, lets hope this fix gets in on time.

**Comment by stanleytsang-amd** [comment]
> > > @stanleytsang-amd It works fine on our CI, can you share the Github/math-ci.rocm build errors with me if they are relevant (I don't have access to CI results)?
> > 
> > 
> > The test failures are the warp_sort and block_sort tests, from [36a4d35](https://github.com/ROCmSoftwarePlatform/rocPRIM/commit/36a4d355b3ff1d6d64a7c308d0a0798a855679c3). I had tried to get it cherry-picked to 5.3 in a while ago but it was deemed non-critical. Thankfully there are no new failures from this PR so I think it is good from my perspective - I still need to convince the 5.3 managers to allow this cherry-pick. The deadline has passed.
> 
> Alright, hmm the [36a4d35](https://github.com/ROCmSoftwarePlatform/rocPRIM/commit/36a4d355b3ff1d6d64a7c308d0a0798a855679c3) seems critical to me, but maybe the 5.3 managers believe this small-types vectorization compiler bug will be fixed in the next 5.3 release, so that a patch for this compiler bug is not needed in rocPRIM?
> 
> Anyways, lets hope this fix gets in.

Agreed with you there, I really wanted the warp_sort and block_sort workaround in for 5.3.  Unfortunately for cherry-picks the project managers usually want to see a live case of a customer being directly impacted by the underlying issue (ie. PyTorch, Tensorflow, or other HPC applications) and there wasn't any.

**Comment by stanleytsang-amd** [comment]
Update: I've been instructed to merge in the PR but it is technically not approved yet - there is still no guarantee it will make it into 5.3.2.  Will update again once I know more.

**Pull request merged**
