### PR TITLE
Update benchmark config tuning

### PR DESCRIPTION
**Pull request by neon60**
Update benchmark config tuning

### CODE REVIEW

**Review by doctorcolinsmith — APPROVED** [review]

**Review by saadrahim — CHANGES_REQUESTED** [review]
We really need to have CI check copyrights.

**Comment by neon60** [comment]
Some of these changes our already in the other PR. Let's merge in this first:
https://github.com/ROCmSoftwarePlatform/rocPRIM/pull/235

**Review by saadrahim — APPROVED** [review]

**Comment by neon60** [comment]
@stanleytsang-amd  We already merged in lot of changes from this PR. I will reach this PR clean up soon.

**Comment by neon60** [comment]
We already merged in:
https://github.com/ROCmSoftwarePlatform/rocPRIM/pull/233/commits/2cd1dd95c669b25cbaa20b606336f61800680161

**Pull request closed without merging**
